services:
  caddy:
    image: caddy:latest
    container_name: global_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      INNGEST_AUTH_HASH: ${INNGEST_AUTH_HASH}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:
    external: true

volumes:
  caddy_data:
  caddy_config:
